name: design_system
description: A sample command-line application.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^3.0.0
  test: ^1.24.0
